# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestwebpro():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testwebpro(self):
    self.driver.get("https://devalv.in/WEBPROLANJUT/index.php")
    self.driver.set_window_size(1722, 928)
    self.driver.find_element(By.LINK_TEXT, "Login Admin").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    self.driver.find_element(By.NAME, "password").send_keys("admin")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").click()
    element = self.driver.find_element(By.NAME, "username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").click()
    element = self.driver.find_element(By.NAME, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Daftar Ruangan").click()
    self.driver.find_element(By.LINK_TEXT, "About").click()
    self.driver.find_element(By.LINK_TEXT, "Daftar Ruangan").click()
    self.driver.find_element(By.LINK_TEXT, "AA204").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Informasi Ruangan").click()
    self.driver.find_element(By.ID, "kapasitas").click()
    self.driver.find_element(By.ID, "kapasitas").send_keys("35")
    self.driver.find_element(By.CSS_SELECTOR, "div > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(10) a:nth-child(1)").click()
    self.driver.find_element(By.NAME, "smt").click()
    self.driver.find_element(By.NAME, "smt").click()
    self.driver.find_element(By.NAME, "smt").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "div > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(10) a:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.NAME, "smt").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "div > input").click()
  
